### ISSUE TITLE
Does not execute.

### ISSUE THREAD

**Issue by MuhammadMuneeb007** [shz9/viprs#4]
Traceback (most recent call last):
  File "viprs.py", line 2, in <module>
    import viprs as vp
  File "/home/muneeb/Desktop/PRSTOOLS/PRS playground/viprs.py", line 17, in <module>
    v = vp.VIPRS(gdl)
AttributeError: partially initialized module 'viprs' has no attribute 'VIPRS' (most likely due to a circular import)

**Comment by MuhammadMuneeb007** [comment]
I changed the conda environment name from viprs to random and the code file name as well from viprs.py to v.py
